services:
  - type: web
    name: ai-pdf-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: MONGODB_URI_FIRST
        sync: false
      - key: MONGODB_URI_PASS
        sync: false
      - key: MONGODB_URI_LAST
        sync: false
      - key: SECRET_KEY
        sync: false
